### ISSUE TITLE
Dependency on private package Octopus.ShellFish

### ISSUE THREAD

**Issue by uglybugger** [OctopusDeploy/OctoVersion#28]
It looks like this package reference crept in when the runner was refactored (#12). This makes it impossible for people outside of Octopus to install/restore OctoVersion.

**Comment by uglybugger** [comment]
@Silcoish Was the intention to publish the `Octopus.ShellFish` NuGet package as well? That might be the simplest approach here.

**Comment by matt-richardson** [comment]
Update - this is blocked as we're having trouble uploading the package. 
But, as soon as we get past that, we should be in a good place to fix this.

**Comment by DamianMac** [comment]
A year later though. As the person outside of Octopus trying to use it, I moved on.

**Comment by matt-richardson** [comment]
Sorry 😢 
Too many things to do, not enough time.
