### ISSUE TITLE
How to get the branch with Nuke

### ISSUE THREAD

**Issue by valadas** [OctopusDeploy/OctoVersion#82]
I love that there is a Nuke usage documentation. It work perfectly for a local build but how do I get github actions to inject the branch name in that parameter?

**Comment by matt-richardson** [comment]
Hi @valadas, thanks for reaching out!

I see you're chatting to @matkoch in the nuke slack, and he's given you some tips on how to make the parameters work well here, but if that doesn't pan out, you can check out an example where we're using it in github actions over [here](https://github.com/OctopusDeploy/UsernamePasswordAuthenticationProvider/blob/main/.github/workflows/main.yml) (and the corresponding [nuke build code](https://github.com/OctopusDeploy/UsernamePasswordAuthenticationProvider/blob/main/build/Build.cs)).

Hope that helps!

**Comment by valadas** [comment]
Yes, ended up using this code to keep the Nuke awesome automatic yaml generation :)

```
[GitRepository]
    readonly GitRepository GitRepository;

    string Branch => GitRepository.Branch;
    
    [OctoVersion(
        BranchParameter = nameof(Branch),
        Framework = "net6.0")]
    readonly OctoVersionInfo OctoVersion;
```

**Comment by matt-richardson** [comment]
btw, if you're bored, I wont say no to a PR that adds some info about this to the readme ;)

**Comment by valadas** [comment]
I am not bored, but happy to submit that :)

**Comment by valadas** [comment]
Submitted, thanks @matt-richardson
